version: '2.2'
services:
  web-poem-tests:
    build:
      context: .
      dockerfile: Dockerfile.poem-react-tests
    image: argo.registry:5000/epel-7-poem
    container_name: poem-react-tests
    hostname: poem-react-test
    tty: true
    stdin_open: true
    depends_on:
      - db-poem-tests
    volumes:
      - /dev/log:/dev/log
      - /etc/localtime:/etc/localtime:ro
      - ../:/mnt/poem-source:rw
      - ./execute-backend-tests.sh:/home/jenkins/execute-backend-tests.sh
      - ./execute-frontend-tests.sh:/home/jenkins/execute-frontend-tests.sh
      - ./poem-install.sh:/home/jenkins/poem-install.sh
  db-poem-tests:
    container_name: poem-react-tests-postgres10
    image: postgres:10
