FROM rockylinux:9
MAINTAINER dvrcic@srce.hr
RUN groupadd jenkins -g 1000 && useradd -u 1000 -g 1000 jenkins -m -d /home/jenkins
RUN passwd -d root
RUN dnf -y makecache; dnf -y update; dnf clean all
RUN dnf -y install epel-release rocky-repos && \
    dnf -y install \
      ack \
      git \
      htop \
      make \
      httpd httpd-devel \
      mod_ssl \
      psmisc \
      python3-devel \
      python3-mod_wsgi \
      python3-pip \
      python3-setuptools \
      sudo
RUN dnf -y makecache
RUN dnf -y install \
      supervisor
RUN passwd -d apache; usermod --shell /bin/bash apache
RUN python3.9 -m venv /opt/poetry-tool/
RUN sh -c '\
  . /opt/poetry-tool/bin/activate \
  && pip install -U pip \
  && pip install -U poetry==1.*'
RUN ln -s /opt/poetry-tool/bin/poetry /usr/local/bin/
RUN dnf module install -y nodejs:20
COPY venv_poem.sh /etc/profile.d/
RUN python3.9 -m venv /opt/poem
RUN sh -c '\
  . /opt/poem/bin/activate \
  && pip install -U pip'
RUN mkdir -p /opt/poem/var/log && chmod a+rw /opt/poem/var/log
WORKDIR /home/jenkins
COPY \
    fake-secret \
    poem.conf \
    entrypoint.sh \
    /home/jenkins/
COPY apache/poem-apache.ini /etc/supervisord.d/
COPY apache/poem.conf /etc/httpd/conf.d/
RUN echo "jenkins ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers
USER jenkins
ENTRYPOINT ["/home/jenkins/entrypoint.sh"]

# vim: ft=dockerfile
