services:
  web-poem-tests:
    build:
      context: .
      dockerfile: Dockerfile.poem-react-tests
    image: poem-react-tests-webapp
    container_name: poem-react-tests-webapp
    hostname: poem-react-test
    tty: true
    stdin_open: true
    depends_on:
      - db-poem-tests
    volumes:
      - /dev/log:/dev/log
      - /etc/localtime:/etc/localtime:ro
      - ../:/mnt/poem-source:rw
      - ./execute-backend-tests.sh:/home/jenkins/execute-backend-tests.sh
      - ./execute-frontend-tests.sh:/home/jenkins/execute-frontend-tests.sh
      - ./poem-install.sh:/home/jenkins/poem-install.sh
  db-poem-tests:
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: poem-react-tests-postgres16
    image: postgres:16
