# Generated by Django 2.2.5 on 2019-10-10 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=191)),
                ('serialized_data', models.TextField()),
                ('object_repr', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('user', models.CharField(max_length=32)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='MetricTemplateType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the probe.', max_length=128, unique=True)),
                ('version', models.CharField(help_text='Version of the probe.', max_length=28)),
                ('nameversion', models.CharField(help_text='Name, version tuple.', max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('comment', models.CharField(max_length=512)),
                ('repository', models.CharField(max_length=512)),
                ('docurl', models.CharField(max_length=512)),
                ('user', models.CharField(blank=True, max_length=32)),
                ('datetime', models.DateTimeField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Probe',
            },
        ),
        migrations.CreateModel(
            name='MetricTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('probeversion', models.CharField(max_length=128)),
                ('parent', models.CharField(max_length=128)),
                ('probeexecutable', models.CharField(max_length=128)),
                ('config', models.CharField(max_length=1024)),
                ('attribute', models.CharField(max_length=1024)),
                ('dependency', models.CharField(max_length=1024)),
                ('flags', models.CharField(max_length=1024)),
                ('files', models.CharField(max_length=1024)),
                ('parameter', models.CharField(max_length=1024)),
                ('fileparameter', models.CharField(max_length=1024)),
                ('cloned', models.CharField(max_length=128, null=True)),
                ('mtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplateType')),
                ('probekey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poem_super_admin.History')),
            ],
            options={
                'verbose_name': 'Metric template',
            },
        ),
        migrations.CreateModel(
            name='ExtRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version', max_length=128)),
                ('probeid', models.BigIntegerField()),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.History')),
            ],
        ),
    ]
