# Generated by Django 2.2.5 on 2019-10-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrictemplate',
            name='cloned',
        ),
    ]
