# Generated by Django 2.0.13 on 2019-07-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('poem_super_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version', max_length=128)),
                ('probeid', models.BigIntegerField()),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reversion.Revision')),
            ],
        ),
    ]
