# Generated by Django 2.2.5 on 2019-10-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0002_remove_metrictemplate_cloned'),
    ]

    operations = [
        migrations.CreateModel(
            name='YumRepo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
