# Generated by Django 2.0.13 on 2019-07-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        ('poem_super_admin', '0002_extrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('probeversion', models.CharField(max_length=128)),
                ('parent', models.CharField(max_length=128)),
                ('probeexecutable', models.CharField(max_length=128)),
                ('config', models.CharField(max_length=1024)),
                ('attribute', models.CharField(max_length=1024)),
                ('dependency', models.CharField(max_length=1024)),
                ('flags', models.CharField(max_length=1024)),
                ('files', models.CharField(max_length=1024)),
                ('parameter', models.CharField(max_length=1024)),
                ('fileparameter', models.CharField(max_length=1024)),
                ('cloned', models.CharField(max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Metric template',
            },
        ),
        migrations.CreateModel(
            name='MetricTemplateAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metrictemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MetricTemplateConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=384, null=True)),
                ('value', models.CharField(blank=True, max_length=384, null=True)),
                ('metrictemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MetricTemplateDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metrictemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MetricTemplateFileParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metrictemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MetricTemplateFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metrictemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MetricTemplateFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metrictemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MetricTemplateParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metrictemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MetricTemplateParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Parent metric', max_length=384, null=True)),
                ('metrictemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MetricTemplateProbeExecutable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Probe executable', max_length=384, null=True)),
                ('metrictemplate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MetricTemplateType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='metrictemplate',
            name='mtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplateType'),
        ),
        migrations.AddField(
            model_name='metrictemplate',
            name='probekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reversion.Version'),
        ),
    ]
