# Generated by Django 2.2.5 on 2019-10-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0003_yumrepo'),
    ]

    operations = [
        migrations.AddField(
            model_name='yumrepo',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
