# Generated by Django 2.2.5 on 2019-09-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0003_metrictemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrictemplateconfig',
            name='metrictemplate',
        ),
        migrations.RemoveField(
            model_name='metrictemplatedependency',
            name='metrictemplate',
        ),
        migrations.RemoveField(
            model_name='metrictemplatefileparameter',
            name='metrictemplate',
        ),
        migrations.RemoveField(
            model_name='metrictemplatefiles',
            name='metrictemplate',
        ),
        migrations.RemoveField(
            model_name='metrictemplateflags',
            name='metrictemplate',
        ),
        migrations.RemoveField(
            model_name='metrictemplateparameter',
            name='metrictemplate',
        ),
        migrations.RemoveField(
            model_name='metrictemplateparent',
            name='metrictemplate',
        ),
        migrations.RemoveField(
            model_name='metrictemplateprobeexecutable',
            name='metrictemplate',
        ),
        migrations.DeleteModel(
            name='MetricTemplateAttribute',
        ),
        migrations.DeleteModel(
            name='MetricTemplateConfig',
        ),
        migrations.DeleteModel(
            name='MetricTemplateDependency',
        ),
        migrations.DeleteModel(
            name='MetricTemplateFileParameter',
        ),
        migrations.DeleteModel(
            name='MetricTemplateFiles',
        ),
        migrations.DeleteModel(
            name='MetricTemplateFlags',
        ),
        migrations.DeleteModel(
            name='MetricTemplateParameter',
        ),
        migrations.DeleteModel(
            name='MetricTemplateParent',
        ),
        migrations.DeleteModel(
            name='MetricTemplateProbeExecutable',
        ),
    ]
