# Generated by Django 2.2.5 on 2019-12-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0004_yumrepo_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=28)),
                ('description', models.CharField(max_length=1024)),
                ('comment', models.CharField(max_length=512)),
                ('repository', models.CharField(max_length=512)),
                ('docurl', models.CharField(max_length=512)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('version_comment', models.TextField(blank=True)),
                ('version_user', models.CharField(max_length=32)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.Probe')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
    ]
