# Generated by Django 2.2.5 on 2019-10-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0005_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrevision',
            name='revision',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.History'),
        ),
    ]
