# Generated by Django 2.2.5 on 2019-12-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0005_probehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probe',
            name='nameversion',
        ),
        migrations.AlterField(
            model_name='probe',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='probe',
            name='version',
            field=models.CharField(max_length=28),
        ),
    ]
