# Generated by Django 2.2.5 on 2019-10-09 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0006_extrevision_revision_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrictemplate',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='metrictemplate',
            name='probekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poem_super_admin.History'),
        ),
    ]
