# Generated by Django 2.2.5 on 2019-12-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0007_metrictemplate_alter_probekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrictemplate',
            name='probeversion',
        ),
    ]
