# Generated by Django 2.2.5 on 2019-12-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0008_remove_metrictemplate_probeversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtRevision',
        ),
    ]
