# Generated by Django 2.2.5 on 2019-12-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0009_delete_extrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricTemplateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('parent', models.CharField(max_length=128)),
                ('probeexecutable', models.CharField(max_length=128)),
                ('config', models.CharField(max_length=1024)),
                ('attribute', models.CharField(max_length=1024)),
                ('dependency', models.CharField(max_length=1024)),
                ('flags', models.CharField(max_length=1024)),
                ('files', models.CharField(max_length=1024)),
                ('parameter', models.CharField(max_length=1024)),
                ('fileparameter', models.CharField(max_length=1024)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('version_comment', models.TextField(blank=True)),
                ('version_user', models.CharField(max_length=32)),
                ('mtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplateType')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.MetricTemplate')),
                ('probekey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poem_super_admin.ProbeHistory')),
            ],
            options={
                'unique_together': {('name', 'probekey')},
            },
        ),
    ]
