# Generated by Django 2.2.5 on 2019-12-09 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0010_metrictemplatehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('version', models.TextField()),
                ('repo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poem_super_admin.YumRepo')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
    ]
