# Generated by Django 2.2.5 on 2019-12-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0012_probe_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='probehistory',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poem_super_admin.Package'),
        ),
    ]
