# Generated by Django 2.2.5 on 2019-12-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0013_probehistory_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probe',
            name='version',
        ),
        migrations.AlterField(
            model_name='probe',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poem_super_admin.Package'),
        ),
    ]
