# Generated by Django 2.2.5 on 2019-12-16 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0014_remove_probe_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probehistory',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poem_super_admin.Package'),
        ),
        migrations.AlterUniqueTogether(
            name='probehistory',
            unique_together={('name', 'package')},
        ),
        migrations.RemoveField(
            model_name='probehistory',
            name='version',
        ),
    ]
