# Generated by Django 2.2.5 on 2019-12-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0015_remove_probehistory_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
