# Generated by Django 2.2.5 on 2019-12-16 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0016_ostag'),
    ]

    operations = [
        migrations.AddField(
            model_name='yumrepo',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poem_super_admin.OSTag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yumrepo',
            name='name',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='yumrepo',
            unique_together={('name', 'tag')},
        ),
    ]
