# Generated by Django 2.2.5 on 2020-02-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0018_package_repos'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='use_present_version',
            field=models.BooleanField(default=False),
        ),
    ]
