# Generated by Django 2.2.12 on 2020-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0021_metrictemplatehistory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricTags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
