# Generated by Django 2.2.12 on 2020-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0023_metrictemplate_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrictemplatehistory',
            name='tags',
            field=models.ManyToManyField(to='poem_super_admin.MetricTags'),
        ),
    ]
