# Generated by Django 3.2.15 on 2022-09-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0025_alter_metrictags_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPort',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
            ],
        ),
    ]
