# Generated by Django 3.2.19 on 2024-06-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0027_webapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrictemplate',
            name='fileparameter',
        ),
        migrations.RemoveField(
            model_name='metrictemplate',
            name='files',
        ),
    ]
