# Generated by Django 3.2.19 on 2024-07-08 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0028_metrictemplate_remove_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrictemplatehistory',
            name='fileparameter',
        ),
        migrations.RemoveField(
            model_name='metrictemplatehistory',
            name='files',
        ),
    ]
