site_name: POEM documentation [V1]
site_url: http://argoeu.github.io/
repo_url: https://github.com/ARGOeu/poem-2
site_description: ARGO is a lightweight service for Service Level Monitoring designed for medium and large sized e-Infrastructures.
remote_branch: master
copyright: Copyright © 2014 - 2020 SRCE

nav:
- Basic Information:
    - Home: index.md
- SuperAdmin POEM:
    - Administration: superadmin_administration.md
        - Default ports: superadmin_default_ports.md
        - Users: superadmin_users.md
    - Tenants: superadmin_tenants.md
    - YUM repos: superadmin_repos.md
    - Packages: superadmin_packages.md
    - Probes: superadmin_probe.md
    - Metric templates: superadmin_metric_templates.md

- Tenant POEM:
    - Administration: tenant_administration.md
        - Metric configuration overrides: tenant_metric_overrides.md
        - Probe candidates: tenant_probe_candidates.md
        - Users: tenant_users.md
        - Groups of resources: tenant_groups_of_resources.md
        - Packages: tenant_packages.md
    - Probes: tenant_probes.md
    - Metrics: tenant_metrics.md
    - Aggregation profiles: tenant_aggregation_profiles.md
    - Metric profiles: tenant_metric_profiles.md
    - Thresholds profiles: tenant_thresholds_profiles.md
    - Operations profiles: tenant_operations_profiles.md

- Guides:
    - SuperAdmin POEM guide: superadmin_guide.md
    - Tenant POEM guide: tenant_guide.md

theme: readthedocs
