# Generated by Django 3.2.18 on 2023-03-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_change_tenant_add_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='combined',
            field=models.BooleanField(default=False),
        ),
    ]
