# Generated by Django 2.0.9 on 2019-04-29 11:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('reversion', '0001_squashed_0004_auto_20160611_1202'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Aggregation profile.', max_length=128)),
                ('apiid', models.CharField(help_text='WEB-API ID of Aggregation profile', max_length=128)),
                ('groupname', models.CharField(default='', max_length=128)),
            ],
            options={
                'permissions': (('aggregationsown', 'Read/Write/Modify'),),
            },
        ),
        migrations.CreateModel(
            name='ExtRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version', max_length=128)),
                ('probeid', models.BigIntegerField()),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reversion.Revision')),
            ],
        ),
        migrations.CreateModel(
            name='GroupOfAggregations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('aggregations', models.ManyToManyField(blank=True, to='poem.Aggregation')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'Group of aggregations',
                'verbose_name_plural': 'Groups of aggregations',
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupOfMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Group of metrics',
                'verbose_name_plural': 'Groups of metrics',
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupOfProbes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'Group of probes',
                'verbose_name_plural': 'Groups of probes',
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='GroupOfProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'Group of profiles',
                'verbose_name_plural': 'Groups of profiles',
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('probeversion', models.CharField(max_length=128)),
                ('parent', models.CharField(max_length=128)),
                ('probeexecutable', models.CharField(max_length=128)),
                ('config', models.CharField(max_length=1024)),
                ('attribute', models.CharField(max_length=1024)),
                ('dependancy', models.CharField(max_length=1024)),
                ('flags', models.CharField(max_length=1024)),
                ('files', models.CharField(max_length=1024)),
                ('parameter', models.CharField(max_length=1024)),
                ('fileparameter', models.CharField(max_length=1024)),
                ('cloned', models.CharField(max_length=128, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='poem.GroupOfMetrics')),
            ],
            options={
                'verbose_name': 'Metric',
            },
        ),
        migrations.CreateModel(
            name='MetricAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='MetricConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=384, null=True)),
                ('value', models.CharField(blank=True, max_length=384, null=True)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poem.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='MetricDependancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='MetricFileParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='MetricFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='MetricFlags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='MetricInstance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_flavour', models.CharField(max_length=128)),
                ('metric', models.CharField(max_length=128)),
                ('vo', models.CharField(blank=True, max_length=128, null=True)),
                ('fqan', models.CharField(blank=True, max_length=128, null=True, verbose_name='FQAN')),
            ],
            options={
                'ordering': ['service_flavour', 'metric', 'vo', 'fqan'],
            },
        ),
        migrations.CreateModel(
            name='MetricParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=384)),
                ('value', models.CharField(max_length=384)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='MetricParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Parent metric', max_length=384, null=True)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poem.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='MetricProbeExecutable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Probe executable', max_length=384, null=True)),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='poem.Metric')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'permissions': (('metricsown', 'Read/Write/Modify'),),
            },
        ),
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the probe.', max_length=128, unique=True)),
                ('version', models.CharField(help_text='Version of the probe.', max_length=28)),
                ('nameversion', models.CharField(help_text='Name, version tuple.', max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('comment', models.CharField(max_length=512)),
                ('repository', models.CharField(max_length=512)),
                ('docurl', models.CharField(max_length=512)),
                ('group', models.CharField(max_length=1024)),
                ('user', models.CharField(blank=True, max_length=32)),
                ('datetime', models.DateTimeField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Probe',
                'permissions': (('probesown', 'Read/Write/Modify'),),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the profile.', max_length=128)),
                ('version', models.CharField(default='1.0', help_text='Multiple versions of the profile can exist (defaults to 1.0).', max_length=10)),
                ('vo', models.CharField(max_length=128, verbose_name='VO')),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('groupname', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Profile',
                'ordering': ['name', 'version'],
                'permissions': (('profileown', 'Read/Write/Modify'),),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=1024)),
                ('service_name', models.CharField(max_length=128)),
                ('service_area', models.CharField(max_length=1024)),
                ('service_version', models.CharField(max_length=1024)),
                ('service_type', models.CharField(max_length=1024)),
                ('component_version', models.CharField(max_length=1024)),
                ('component_name', models.CharField(max_length=1024)),
                ('visible_to_marketplace', models.BooleanField(default=False)),
                ('in_catalogue', models.BooleanField(default=False)),
                ('external_service', models.BooleanField(default=False)),
                ('internal_service', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFlavour',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Service flavour')),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=512, null=True, verbose_name='distinguishedName')),
                ('egiid', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='eduPersonUniqueId')),
                ('displayname', models.CharField(blank=True, max_length=30, null=True, verbose_name='displayName')),
                ('groupsofaggregations', models.ManyToManyField(blank=True, help_text='The groups of aggregations that user will control', related_name='user_set', related_query_name='user', to='poem.GroupOfAggregations', verbose_name='groups of aggregations')),
                ('groupsofmetrics', models.ManyToManyField(blank=True, help_text='The groups of metrics that user will control', related_name='user_set', related_query_name='user', to='poem.GroupOfMetrics', verbose_name='groups of metrics')),
                ('groupsofprobes', models.ManyToManyField(blank=True, help_text='The groups of probes that user will control', related_name='user_set', related_query_name='user', to='poem.GroupOfProbes', verbose_name='groups of probes')),
                ('groupsofprofiles', models.ManyToManyField(blank=True, help_text='The groups of profiles that user will control.', related_name='user_set', related_query_name='user', to='poem.GroupOfProfiles', verbose_name='groups of profiles')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VO',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Virtual organization')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('name', 'version')},
        ),
        migrations.AddField(
            model_name='metricinstance',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_instances', to='poem.Profile'),
        ),
        migrations.AddField(
            model_name='metric',
            name='mtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.MetricType'),
        ),
        migrations.AddField(
            model_name='metric',
            name='probekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reversion.Version'),
        ),
        migrations.AddField(
            model_name='metric',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Tags'),
        ),
        migrations.AddField(
            model_name='groupofprofiles',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='poem.Profile'),
        ),
        migrations.AddField(
            model_name='groupofprobes',
            name='probes',
            field=models.ManyToManyField(blank=True, to='poem.Probe'),
        ),
        migrations.AddField(
            model_name='groupofmetrics',
            name='metrics',
            field=models.ManyToManyField(blank=True, to='poem.Metrics'),
        ),
        migrations.AddField(
            model_name='groupofmetrics',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='metricinstance',
            unique_together={('profile', 'service_flavour', 'metric', 'fqan')},
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together={('name', 'tag')},
        ),
    ]
