# Generated by Django 2.2.5 on 2019-10-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupofmetrics',
            name='metrics',
        ),
    ]
