# Generated by Django 2.2.5 on 2019-10-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0003_metric_change_group_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metrics',
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'permissions': (('metricsown', 'Read/Write/Modify'),), 'verbose_name': 'Metric'},
        ),
    ]
