# Generated by Django 2.0.7 on 2018-11-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_reversion_dbfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='metric',
            name='mtype',
            field=models.ForeignKey(default=1, null=False, on_delete=django.db.models.deletion.CASCADE, to='poem.MetricType'),
            preserve_default=False,
        ),
    ]
