# Generated by Django 2.0.13 on 2019-07-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0005_refactor_metricinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupofprofiles',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='groupofprofiles',
            name='profiles',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='VO',
        ),
        migrations.DeleteModel(
            name='GroupOfProfiles',
        ),
    ]
