# Generated by Django 2.2.5 on 2019-11-06 11:16

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('poem', '0005_tenanthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdsProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('apiid', models.CharField(max_length=128)),
                ('groupname', models.CharField(default='', max_length=128)),
            ],
            options={
                'permissions': (('thresholdsprofilesown', 'Read/Write/Modify'),),
            },
        ),
        migrations.CreateModel(
            name='GroupOfThresholdsProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions')),
                ('thresholdsprofiles', models.ManyToManyField(blank=True, to='poem.ThresholdsProfiles')),
            ],
            options={
                'verbose_name': 'Group of thresholds profiles',
                'verbose_name_plural': 'Groups of thresholds profiles',
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
