# Generated by Django 2.2.5 on 2019-11-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0006_groupofthresholdsprofiles_thresholdsprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='groupsofthresholdsprofiles',
            field=models.ManyToManyField(blank=True, help_text='The groups of thresholds profiles that user will control', related_name='user_set', related_query_name='user', to='poem.GroupOfThresholdsProfiles', verbose_name='groups of thresholds profiles'),
        ),
    ]
