# Generated by Django 2.0.7 on 2018-11-18 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0007_allownull_metricgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='probekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reversion.Version'),
        ),
    ]
