# Generated by Django 2.0.13 on 2019-07-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0007_remove_userprofile_groupsofprobes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrevision',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='groupofprobes',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='groupofprobes',
            name='probes',
        ),
        migrations.DeleteModel(
            name='ExtRevision',
        ),
        migrations.DeleteModel(
            name='GroupOfProbes',
        ),
        migrations.DeleteModel(
            name='Probe',
        ),
    ]
