# Generated by Django 2.2.5 on 2019-12-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0008_metric_alter_probekey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='probeversion',
        ),
    ]
