# Generated by Django 2.0.7 on 2018-11-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0008_probe_ondeletenull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probe',
            name='name',
            field=models.CharField(help_text='Name of the probe.', max_length=128, unique=True),
        ),
    ]
