# Generated by Django 2.0.13 on 2019-07-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0008_removed_probe_extrevision_groupofprobes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='cloned',
        ),
    ]
