# Generated by Django 2.2.5 on 2020-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0009_remove_metric_probeversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='component_name',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='component_version',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_category',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_version',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
