# Generated by Django 2.0.13 on 2019-08-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0009_remove_metric_cloned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricattribute',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='metricconfig',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='metricfileparameter',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='metricfiles',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='metricflags',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='metricparameter',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='metricparent',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='metricprobeexecutable',
            name='metric',
        ),
        migrations.DeleteModel(
            name='MetricAttribute',
        ),
        migrations.DeleteModel(
            name='MetricConfig',
        ),
        migrations.DeleteModel(
            name='MetricFileParameter',
        ),
        migrations.DeleteModel(
            name='MetricFiles',
        ),
        migrations.DeleteModel(
            name='MetricFlags',
        ),
        migrations.DeleteModel(
            name='MetricParameter',
        ),
        migrations.DeleteModel(
            name='MetricParent',
        ),
        migrations.DeleteModel(
            name='MetricProbeExecutable',
        ),
    ]
