# Generated by Django 2.2.5 on 2020-03-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0010_service_null_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricprofiles',
            name='description',
            field=models.CharField(max_length=1024, default=''),
        ),
    ]
