# Generated by Django 2.0.10 on 2019-02-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0010_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='distinguishedName'),
        ),
    ]
