# Generated by Django 2.2.5 on 2020-03-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0011_metricprofiles_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregation',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='thresholdsprofiles',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
