# Generated by Django 2.2.5 on 2019-09-27 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0011_userprofile_on_delete_do_nothing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetricDependancy',
        ),
    ]
