# Generated by Django 2.2.5 on 2019-10-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0012_delete_metricdependancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='metric',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='metric',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
