# Generated by Django 2.2.5 on 2019-10-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0005_history'),
        ('poem', '0013_delete_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='probekey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poem_super_admin.History'),
        ),
    ]
