# Generated by Django 2.2.12 on 2020-04-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0013_metric_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricprofiles',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
