# Generated by Django 2.2.12 on 2020-05-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0014_metric_profile_description_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='egiid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='eduPersonUniqueId'),
        ),
    ]
