# Generated by Django 2.0.9 on 2019-03-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0015_probe_update_metric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'verbose_name': 'Metric'},
        ),
        migrations.AlterModelOptions(
            name='probe',
            options={'permissions': (('probesown', 'Read/Write/Modify'),), 'verbose_name': 'Probe'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['name', 'version'], 'permissions': (('profileown', 'Read/Write/Modify'),), 'verbose_name': 'Profile'},
        ),
        migrations.AlterField(
            model_name='custuser',
            name='groupsofaggregations',
            field=models.ManyToManyField(blank=True, help_text='The groups of aggregations that user will control', related_name='user_set', related_query_name='user', to='poem.GroupOfAggregations', verbose_name='groups of aggregations'),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='groupsofmetrics',
            field=models.ManyToManyField(blank=True, help_text='The groups of metrics that user will control', related_name='user_set', related_query_name='user', to='poem.GroupOfMetrics', verbose_name='groups of metrics'),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='groupsofprobes',
            field=models.ManyToManyField(blank=True, help_text='The groups of probes that user will control', related_name='user_set', related_query_name='user', to='poem.GroupOfProbes', verbose_name='groups of probes'),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='groupsofprofiles',
            field=models.ManyToManyField(blank=True, help_text='The groups of profiles that user will control', related_name='user_set', related_query_name='user', to='poem.GroupOfProfiles', verbose_name='groups of profiles'),
        ),
        migrations.AlterField(
            model_name='probe',
            name='update_metric',
            field=models.BooleanField(default=False),
        ),
    ]
