# Generated by Django 2.2.12 on 2020-07-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem_super_admin', '0024_metrictemplatehistory_tags'),
        ('poem', '0016_remove_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='tags',
            field=models.ManyToManyField(to='poem_super_admin.MetricTags'),
        ),
    ]
