# Generated by Django 2.0.9 on 2019-03-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0016_probes_update_metric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probe',
            name='update_metric',
        ),
    ]
