# Generated by Django 2.0.13 on 2019-05-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0017_remove_probe_update_metric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_area',
            new_name='service_category',
        ),
    ]
