# Generated by Django 2.2.19 on 2021-04-21 11:04

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('poem', '0017_metric_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Report.', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('apiid', models.CharField(help_text='WEB-API ID of Report', max_length=128)),
                ('groupname', models.CharField(default='', max_length=128)),
            ],
            options={
                'permissions': (('reportsown', 'Read/Write/Modify'),),
            },
        ),
        migrations.CreateModel(
            name='GroupOfReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('reports', models.ManyToManyField(blank=True, to='poem.Reports')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'Group of reports',
                'verbose_name_plural': 'Groups of reports',
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
