# Generated by Django 2.0.13 on 2019-06-07 13:17

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('poem', '0018_rename_servicearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfMetricProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Group of metric profiles',
                'verbose_name_plural': 'Groups of metric profiles',
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='MetricProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Metric profile.', max_length=128)),
                ('apiid', models.CharField(help_text='WEB-API ID of Metric profile', max_length=128)),
                ('groupname', models.CharField(default='', max_length=128)),
            ],
            options={
                'permissions': (('metricprofilessown', 'Read/Write/Modify'),),
            },
        ),
        migrations.AddField(
            model_name='groupofmetricprofiles',
            name='metricprofiles',
            field=models.ManyToManyField(blank=True, to='poem.MetricProfiles'),
        ),
        migrations.AddField(
            model_name='groupofmetricprofiles',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission', verbose_name='permissions'),
        ),
    ]
