# Generated by Django 2.2.19 on 2021-04-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0018_groupofreports_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='groupsofreports',
            field=models.ManyToManyField(blank=True, help_text='The groups of reports that user will control', related_name='user_set', related_query_name='user', to='poem.GroupOfReports', verbose_name='groups of reports'),
        ),
    ]
