# Generated by Django 2.2.19 on 2021-04-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0019_userprofile_groupsofreports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupofreports',
            old_name='metricprofiles',
            new_name='reports',
        ),
    ]
