# Generated by Django 3.2.12 on 2022-04-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0019_userprofile_groupsofreports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceflavour',
            name='description',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='serviceflavour',
            name='name',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Service flavour'),
        ),
    ]
