# Generated by Django 2.0.13 on 2019-07-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0020_user_groupsofmetricprofiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricinstance',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='metricinstance',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='metricinstance',
            name='fqan',
        ),
        migrations.RemoveField(
            model_name='metricinstance',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='metricinstance',
            name='vo',
        ),
    ]
