# Generated by Django 3.2.13 on 2022-05-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0021_remove_metric_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('globalattribute', models.TextField()),
                ('hostattribute', models.TextField()),
                ('metricparameter', models.TextField()),
            ],
        ),
    ]
