# Generated by Django 3.2.14 on 2022-08-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0022_metricconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='probeversion',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
