# Generated by Django 3.2.18 on 2023-04-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0026_delete_serviceflavour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeCandidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('docurl', models.URLField(max_length=1024)),
                ('rpm', models.CharField(max_length=1024)),
                ('yum_baseurl', models.URLField(max_length=1024)),
                ('command', models.CharField(max_length=2048)),
                ('contact', models.EmailField(max_length=254)),
                ('status', models.CharField(default='submitted', max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True, max_length=32)),
                ('last_update', models.DateTimeField(auto_now=True, max_length=32)),
            ],
        ),
    ]
