# Generated by Django 3.2.19 on 2023-05-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0027_probecandidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probecandidate',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
