# Generated by Django 3.2.19 on 2023-06-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0028_alter_probecandidate_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeCandidateStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
