# Generated by Django 3.2.19 on 2023-06-01 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0029_probecandidatestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probecandidate',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.probecandidatestatus'),
        ),
    ]
