# Generated by Django 3.2.19 on 2023-07-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0030_alter_probecandidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='probecandidate',
            name='service_type',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
