# Generated by Django 3.2.19 on 2023-07-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0031_probecandidate_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='probecandidate',
            name='devel_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
