# Generated by Django 3.2.19 on 2023-08-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0034_probecandidate_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='probecandidate',
            name='deployed_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='probecandidate',
            name='processing_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='probecandidate',
            name='rejected_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='probecandidate',
            name='submitted_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='probecandidate',
            name='testing_sent',
            field=models.BooleanField(default=False),
        ),
    ]
