# Generated by Django 3.2.19 on 2023-08-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0035_probecandidate_mail_sent_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='probecandidate',
            name='script',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
